server:
  port: 10000

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
  application:
    name: eureka-server #服务名称


###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: false
    ###是否需要从eureka上检索服务
    fetch-registry: false
#  instance:
#    #设置使用IP
#    prefer-ip-address: true
#    #设置外网IP号
#    ip-address: 134.175.244.202
#    #设置外网端口号
#    non-secure-port: 10012
#    #配置文件中开启hystrix
